# Generated by Django 2.2.4 on 2019-08-31 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='title_minutes',
            new_name='time_minutes',
        ),
    ]
